name: Build and Deply Code

on: [push, pull_request]

jobs:
  job1:
    env:
      SECRET_KEY: django-insecure--n6t$=^+p+(b188e-5phqheprmpikg-sidiyu8hgrbe64u)akh
      DEBUG: True
      EMAIL_USE_SSL: True
      EMAIL_HOST: smtpout.secureserver.net
      EMAIL_PORT: 465
      EMAIL_HOST_USER: admin@prodev.pro
      EMAIL_HOST_PASSWORD: Rehan876685$
      DEFAULT_FROM_EMAIL: Rehan <admin@prodev.pro>
      runs-on: ubuntu-latest
    steps:
      - name: pulling git repo
        uses: actions/checkout@v2
      - name: Install python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: update pip
        run: python3 -m pip install --upgrade pip
      - name: install all dependencies
        run: pip install -r requirements.txt
      - name: testing our code
        run: python3 manage.py test