name: CI/CD pipeline for django-blog-api

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: pulling git repo
        uses: actions/checkout@v2
      - name: Install python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: updating packages
        run: apt update
        run: python3 -m pip install --upgrade pip
      - name: setting up docker
        uses: docker-practice/actions-setup-docker@master
      - name: login to docker hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: building image for deployment
        run: docker build -t django-blog-api:0.1.0 .